// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenScience.Data;

namespace OpenScience.Data.Migrations.AppLog
{
    [DbContext(typeof(AppLogContext))]
    [Migration("20200121082442_InitialLogMigration")]
    partial class InitialLogMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("OpenScience.Data.Logs.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("IP")
                        .HasColumnName("ip");

                    b.Property<DateTime>("LogDate")
                        .HasColumnName("logdate");

                    b.Property<string>("Message")
                        .HasColumnName("message");

                    b.Property<int>("Type")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .HasColumnName("url");

                    b.Property<string>("UserAgent")
                        .HasColumnName("useragent");

                    b.Property<int?>("UserId")
                        .HasColumnName("userid");

                    b.Property<string>("Verb")
                        .HasColumnName("verb");

                    b.HasKey("Id");

                    b.ToTable("log");
                });
#pragma warning restore 612, 618
        }
    }
}
